### ISSUE TITLE
"ImportError: No module named _caffe " during Postgres migrate.

### ISSUE THREAD

**Issue by siddas27** [Cloud-CV/Fabrik#303]
``
(Fabrik) siddharth@joker:/media/siddharth/SiD/project/Fabrik$ python manage.py makemigrations caffe_app
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/media/siddharth/SiD/project/Fabrik/ide/urls.py", line 9, in <module>
    url(r'^caffe/', include('caffe_app.urls')),
  File "/home/siddharth/Fabrik/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/media/siddharth/SiD/project/Fabrik/caffe_app/urls.py", line 2, in <module>
    from views.import_prototxt import import_prototxt
  File "/media/siddharth/SiD/project/Fabrik/caffe_app/views/import_prototxt.py", line 5, in <module>
    from caffe.proto import caffe_pb2
  File "/home/siddharth/caffe/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/siddharth/caffe/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe``
[image](https://imgur.com/a/o9cq9)

**Comment by deshraj** [comment]
@siddas27: it doesn't look like a cudnn error. I think you were not able to install caffe correctly on your PC. Please try again and watch for any cudnn errors.

**Comment by saurabhpal97** [comment]
I had the same problem on my laptop, try installing Caffe from source.

**Comment by utsavgarg** [comment]
@siddas27 Please discuss setup issues on the [Gitter](https://gitter.im/Cloud-CV/Fabrik) channel.
