### ISSUE TITLE
The page is blank

### ISSUE THREAD

**Issue by hanghi** [Cloud-CV/Fabrik#339]
I followed the guide, and when I open Fabrik page (http://127.0.0.1:8000 on my machine), it's blank.
I see this when loading the page: "GET /static/bundle/bundle.js HTTP/1.1" 404 1661
How can I fix this? I really need this tool to understand the model :( .
Thank you.

**Comment by MuLx10** [comment]
@hanghi  build the webpack
`webpack --progress --watch --colors`

**Comment by hanghi** [comment]
Hi, 
I tried, but it said:
`The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D`

Then, I tried to install webpack-cli 
' sudo npm install -g webpack-cli'

And run:
`webpack-cli --progress --watch --colors`

But there is still error:
`/usr/lib/node_modules/webpack-cli/bin/webpack.js:242
				throw err;
				^

Error: invalid "instanceof" keyword value Promise
    at getConstructor (/usr/lib/node_modules/webpack/node_modules/ajv-keywords/keywords/instanceof.js:52:11)
    at Ajv.compile (/usr/lib/node_modules/webpack/node_modules/ajv-keywords/keywords/instanceof.js:21:27)
    at Object.useCustomRule (/usr/lib/node_modules/webpack/node_modules/ajv/lib/compile/index.js:289:26)
    at Object.generate_custom [as code] (/usr/lib/node_modules/webpack/node_modules/ajv/lib/dotjs/custom.js:31:24)
    at Object.generate_validate [as validate] (/usr/lib/node_modules/webpack/node_modules/ajv/lib/dotjs/validate.js:228:37)
    at Object.generate_anyOf [as code] (/usr/lib/node_modules/webpack/node_modules/ajv/lib/dotjs/anyOf.js:34:27)
    at generate_validate (/usr/lib/node_modules/webpack/node_modules/ajv/lib/dotjs/validate.js:228:37)
    at localCompile (/usr/lib/node_modules/webpack/node_modules/ajv/lib/compile/index.js:99:22)
    at Ajv.compile (/usr/lib/node_modules/webpack/node_modules/ajv/lib/compile/index.js:67:13)
    at _compile (/usr/lib/node_modules/webpack/node_modules/ajv/lib/ajv.js:328:29)
    at Ajv.compile (/usr/lib/node_modules/webpack/node_modules/ajv/lib/ajv.js:114:34)
    at validateObject (/usr/lib/node_modules/webpack/lib/validateSchema.js:36:23)
    at validateSchema (/usr/lib/node_modules/webpack/lib/validateSchema.js:31:10)
    at processConfiguredOptions (/usr/lib/node_modules/webpack-cli/bin/convert-argv.js:156:48)
    at module.exports (/usr/lib/node_modules/webpack-cli/bin/convert-argv.js:150:10)
    at yargs.parse (/usr/lib/node_modules/webpack-cli/bin/webpack.js:239:39)
    at Object.parse (/usr/lib/node_modules/webpack-cli/node_modules/yargs/yargs.js:543:18)
    at /usr/lib/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/usr/lib/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
`
I have no idea about this :(

**Comment by MuLx10** [comment]
try to install webpack in the directory `npm i -D webpack-cli`

**Comment by hanghi** [comment]
I followed what you say, and met this error

`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.output.path: The provided value "./ide/static/bundle/" is not an absolute path!
   -> The output directory as **absolute path** (required).
`
I think Fabrik should have an online version :(

**Comment by ashar6194** [comment]
I am new to node.js, and I am facing the same issue, cannot get webpack to work :/.

**Comment by MuLx10** [comment]
make sure that webpack  is installed and its version is correct .If it doesn't work try installing `webpack@1.15.0` instead of the latest version.

**Comment by Ram81** [comment]
@hanghi @ashar6194 you can post issues with setup on our gitter channel [here](https://gitter.im/Cloud-CV/Fabrik), closing this.
