### ISSUE TITLE
AttributeError: module 'startup' has no attribute 'run'

### ISSUE THREAD

**Issue by sukhadj** [Cloud-CV/Fabrik#382]
Hello!!
I am trying to install on my Linux 16.04.
I got the following error while migrating:- 

> AttributeError:module 'startup' has no attribute 'run'

Console log : 

> Using Dev settings
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sukhad/Fabrik/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/sukhad/Fabrik/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/sukhad/Fabrik/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/sukhad/Fabrik/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/sukhad/Fabrik/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/sukhad/Fabrik/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/sukhad/Workspace/GithHub/Fabrik/keras_app/apps.py", line 11, in <module>
    startup.run()
AttributeError: module 'startup' has no attribute 'run'

Any solution how to solve this?
Thanks.

**Comment by Ram81** [comment]
@sukhadj please try setting up using python 2.7. And for setup related issues please post on [gitter](https://gitter.im/Cloud-CV/Fabrik) channel.
