### ISSUE TITLE
Celery workers crashes if tried to export model

### ISSUE THREAD

**Issue by seventeen-iterator** [Cloud-CV/Fabrik#457]
I've made installation steps for the virtual environment, described in `README.md`. Loaded model (I was picking the ones that don't contain any recurrence) from the zoo folder and tried to export it. Neither Caffe, Keras, nor Tensorflow exports worked. Nothing happens after the click on the front-end, but celery worker crashes with the following error:
```
[2018-11-17 09:55:17,608: ERROR/MainProcess] Unrecoverable error: AttributeError("'unicode' object has no attribute 'iteritems'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 1019, in on_readable
    self._callbacks[queue](message)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 534, in _callback
    self.qos.append(message, message.delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 146, in append
    pipe.zadd(self.unacked_index_key, delivery_tag, time()) \
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/usr/local/lib/python2.7/dist-packages/redis/_compat.py", line 94, in iteritems
    return x.iteritems()
AttributeError: 'unicode' object has no attribute 'iteritems'
```

On the other hand export doesn't work on fabrik.cloudcv.org as well. Could the error above be the reason for that bug? #448

**Comment by seventeen-iterator** [comment]
I was running on Debian 9. Might be the same for Ubuntu. Does not depend on browser since it's backend problem.
