### ISSUE TITLE
"docker-compose up --build" throws DistributionNotFound error

### ISSUE THREAD

**Issue by Debapriya-Tula** [Cloud-CV/Fabrik#510]
- the expected behaviour
Command should have run with no errors

- the observed behaviour
Throws DistributionNotFound error

Traceback:

> Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docker-compose==1.8.0' distribution was not found and is required by the application

- which operating system and/or browser you're using, if relevant
OS : Ubuntu 16.04
Browser: Chromium

**Comment by LuckyPigeon** [comment]
What's your docker-compose version?

**Comment by Debapriya-Tula** [comment]
1.8.0 build 94f7016.

As was asked to.

**Comment by LuckyPigeon** [comment]
Can your docker-compose run other docker-compose.yml?

**Comment by Debapriya-Tula** [comment]
It was able to run other .yml  files. I tried installing docker-compose again. It did not pose the same error this time. But now I am facing a new error while running docker-compose up as was mentioned in the steps.

```
Starting fabrik_db_1    ... error
908faf63e45b8e07e6871e2724ab097183e4d5dbfbafa): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use
Recreating reactjs      ... done
ERROR: for fabrik_db_1  Cannot start service db: driver failed programming external connectivity on endpoint fabrik_db_1 (db2f8deb65ea53cb7f9396cb8a5adf3a1cce3630ea81d6316f7f8094dd0ab8c9): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

ERROR: for redis  Cannot start service redis: driver failed programming external connectivity on endpoint fabrik_redis_1 (7012507ad4faefe9d4f908faf63e45b8e07e6871e2724ab097183e4d5dbfbafa): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint fabrik_db_1 (db2f8deb65ea53cb7f9396cb8a5adf3a1cce3630ea81d6316f7f8094dd0ab8c9): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

Sorry for closing the issue mistakenly.

**Comment by diningPhilosopher64** [comment]
@Debapriya-Tula , looks like you have been running some other docker/ docker-compose command which is already using the ports (maybe cloudcv/EvalAI ? ). In my case I had been building both cloudcv/EvalAI and cloudcv/Fabrik simultaneously which led to the same error.

Stop other running docker containers and/ or docker-compose commands. That should fix it.

Another way would be to run "docker ps" and see which of the ports are already occupied by which containers and stop them by doing "docker container stop <container name>"
